import { ApiProperty } from '@nestjs/swagger';
import { User } from 'src/users/entities/user.entity';

export class AuthResponse {
  @ApiProperty({
    example:
      'ileruhsbnflkgjshdfklgjhsdklfjhgpqoweiuqnfsjdfhlshlkjhsdflkghjklsdfg',
    description: `Token generated by the api`,
  })
  access_token: string;
}

export class AuthDto {
  @ApiProperty({
    example: 'admin',
    description: `Login word`,
  })
  userName: string;

  @ApiProperty({
    example: 'admin',
    description: `Your password`,
  })
  password: string;
}

export class LoginPayload {
  id: string;
  userType: number;

  constructor(user: User) {
    this.id = user.id;
    this.userType = user.userType;
  }
}