import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

export class GetUserResponse {
  @ApiProperty({
    example: 'usuario_teste@teste.com',
  })
  @IsString()
  @IsNotEmpty()
  email: string;

  @ApiProperty({
    example: 'usuario_teste',
  })
  @IsString()
  @IsNotEmpty()
  name: string;

  @ApiProperty({
    example: 'user_test',
  })
  @IsString()
  @IsNotEmpty()
  userName: string;
}

export class ValidatedUserWithCodeDTO {
  @ApiProperty({
    example:
      'ileruhsbnflkgjshdfklgjhsdklfjhgpqoweiuqnfsjdfhlshlkjhsdflkghjklsdfg',
    description: `Token generated by the api`,
  })
  access_token: string;
}
